### ISSUE TITLE
Sample Issue file.

### ISSUE THREAD

**Issue by maxbussell** [filetrust/glasswall-engineering-site#49]
I would like to have a sample issue file to test the handling of error codes related to a file that cannot be rebuilt.

A Humpty Dumpty file. So broken it cannot be put back together again.

**Comment by AngusWR** [comment]
Here's a zipped corrupt file used in the s93_test_automation project:


[Corrupted_jpeg_png_mag_no.zip](https://github.com/filetrust/glasswall-engineering-site/files/4764278/Corrupted_jpeg_png_mag_no.zip)

**Comment by asloman** [comment]
Hi @maxbussell did Angus' file answer your question?

**Comment by maxbussell** [comment]
Yeah it does. The file contains issues. Please remove from the archive and give it a proper extension and add it to the sample file list.

**Comment by asloman** [comment]
The file has now gone up.
https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/sample-files
