### ISSUE TITLE
Postman Quick Start - Content Flags set to 0

### ISSUE THREAD

**Issue by maxbussell** [filetrust/glasswall-engineering-site#50]
https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/rebuild/rebuild-quickstart/
The Postman quick start project was really useful, but the content flags are all set to 0. This was confusing when using the sample files as the first response returned a file that isnt sanitised. I propose changing all the switches to 1.

**Comment by gw-sbirch** [comment]
@maxbussell @MattCavey I've updated the values to 1. let me know if you have any issues
