### ISSUE TITLE
Python Quick Start Code is incorrect.

### ISSUE THREAD

**Issue by maxbussell** [filetrust/glasswall-engineering-site#52]
https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/rebuild/rebuild-quickstart

requests isnt a default python library and requires a pip install.

Their is no consistency in the use of tabs/spaces between the code snippets this applies to the other languages as well. I would prefer tabs to be used across all examples.

Forming the request:

- There appears to be a zero space character, preceding with open. This raise a syntax issue when copying the code over. There is also no viable mistake so finding the issue is trick. This needs to be removed.

Executing the request:

- This appears to be duplicate code and isnt needed. 
- Also the semi colon at the end is also not python syntax.

Processing the response:

- The first line has a const this variable declaration is invalid python syntax. (const)
- The comment for the output path is ambiguous. It needs to specify that the path require a file name and extension.

The paths for all file locations should be raw strings in python prefixed with r i.e r"example\string"

It would be nice to have a simple print statement to acknowledge the request was successful and state where the file was written. This is a quick start as a user I would expect some feedback of this sort.

**Comment by AngusWR** [comment]
```py


import json
import os
import requests

api_key = "YOUR_API_KEY"
url = "https://8oiyjy8w63.execute-api.us-west-2.amazonaws.com/Prod/api/rebuild/file"
input_file_path = r"YOUR/INPUT/FILE.docx"
output_file_path = r"YOUR/OUTPUT/FILE.docx"

# Send a file to the Glasswall rebuild/file API
with open(input_file_path, "rb") as f:
    response = requests.post(
        url=url,
        files=[("file", f)],
        headers={
            "x-api-key": api_key,
            "accept": "application/octet-stream"
        }
    )

if response.status_code == 200 and response.content:
    # Glasswall has now sanitised and returned this file
    # Create output directory if it does not already exist
    os.makedirs(os.path.dirname(output_file_path), exist_ok=True)
    # Write the sanitised file to output_file_path
    with open(output_file_path, "wb") as f:
        f.write(response.content)
    print("Successfully wrote file to:", os.path.abspath(output_file_path))
else:
    # An error occurred, raise it
    response.raise_for_status()

```

@maxbussell thoughts? 👍 👎

**Comment by maxbussell** [comment]
Really nice work! Working on my machine :)

Moving all the user config to the top is a nice touch.

One change on line 13 to stay inline with our product naming convention
# Send a file to the Glasswall's Rebuild API

@AngusWR  👍
